ready to pull request
Elgg/community_theme pull request #52
Opened 2020-04-01 00:39 UTC by rjcalifornia

Complete redesign of the elgg community page

2020-04-01 11:10 UTC, jeabakker commented
Do you have some screenshots before/after that would make it somewhat easier to review this PR

2020-04-01 15:35 UTC, rjcalifornia commented
Sure, check out the screenshots:

https://imgur.com/a/XvX08tl

2020-04-09 08:45 UTC, jeabakker requested changes
I found out that the elgg/community_theme isn't the theme used on the Elgg community. Instead it's the elgg/community_pages plugin.

Why did you commit all those assets (+4700 files) are they all used? it not try to limit it to what's actually used or have it being imported a a composer dependency (if available).

Also have a look at some of the remarks i made. I thinks in general it's not a bad improvement, but it can't be accepted in it's current form.

2020-04-09 08:45 UTC, jeabakker commented on .netbeans.xml
> +</auxiliary-configuration>
Why is this this file added?

2020-04-09 08:45 UTC, jeabakker commented on README.md
> +Aalborg theme
It's not the aalborg theme, is a Elgg community theme. Please remove any references to the aalborg theme

2020-04-09 08:45 UTC, jeabakker commented on composer.json
> +    "name": "elgg/aalborg_theme",
this will cause installation issues, since Packagist can't match the registered package with this name

2020-04-09 08:45 UTC, jeabakker commented on manifest.xml
> +	<id>star-admin-theme</id>
this id doesn't match the repo name or the `composer.json` name which will cause installation issues

2020-04-09 08:46 UTC, jeabakker commented
Since this is a PR on the wrong repo i'm going to close this PR, and make sure nobody can accidentally do the same thing.

2020-04-09 08:46 UTC, closed without merging